name: raster
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas >=0.10.2
  - ipykernel
  - rioxarray
  - xarray <=2022.11.0
  - rasterio <=1.3.3
  - seaborn
  - netcdf4
  - osmpythontools >=0.3.5
